const FETCH_DIRECTIVE = "DIRECTIVE/FETCH";
const FETCH_DIRECTIVE_SUCCESS = "DIRECTIVE/FETCH_SUCCESS";
const FETCH_DIRECTIVE_FAILURE = "DIRECTIVE/FETCH_FAILURE";

const types = {
  FETCH_DIRECTIVE,
  FETCH_DIRECTIVE_SUCCESS,
  FETCH_DIRECTIVE_FAILURE
};

export default types;
