const FETCH_PAGES = "PAGES/FETCH";
const FETCH_PAGES_SUCCESS = "PAGES/FETCH_SUCCESS";
const FETCH_PAGES_FAILURE = "PAGES/FETCH_FAILURE";

const types = {
  FETCH_PAGES,
  FETCH_PAGES_SUCCESS,
  FETCH_PAGES_FAILURE
};

export default types;
