const FETCH_COMPETITIONS = "COMPETITIONS/FETCH";
const FETCH_COMPETITIONS_SUCCESS = "COMPETITIONS/FETCH_SUCCESS";
const FETCH_COMPETITIONS_FAILURE = "COMPETITIONS/FETCH_FAILURE";

const types = {
  FETCH_COMPETITIONS,
  FETCH_COMPETITIONS_SUCCESS,
  FETCH_COMPETITIONS_FAILURE
};

export default types;
