const FETCH_CALLUPS = "CALLUPS/FETCH";
const FETCH_CALLUPS_SUCCESS = "CALLUPS/FETCH_SUCCESS";
const FETCH_CALLUPS_FAILURE = "CALLUPS/FETCH_FAILURE";

const types = {
  FETCH_CALLUPS,
  FETCH_CALLUPS_SUCCESS,
  FETCH_CALLUPS_FAILURE
};

export default types;
